service: ecb-sheet

plugins:
  - serverless-apigw-binary
  - serverless-apigwy-binary

custom:
  apigwBinary:
    types:
      - 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'

package:
  exclude:
    - "*/*"

  include:
    - crosscurrency.rb
    - lib/**
    - vendor/**

provider:
  name: aws
  runtime: ruby2.5
  memorySize: 1024 # optional, in MB, default is 1024
  versionFunctions: false # optional, default is true
  stage: dev
  region: eu-north-1

functions:
  crosscurrency:
    handler: crosscurrency.lambda_handler
    events:
      - http:
          path: crosscurrency
          method: get
          contentHandling: CONVERT_TO_BINARY
          request:
            parameters:
              querystrings:
                currency: true
